export const typography = {
  fonts: {
    heading: `'Poppins', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif`,
    body: `'Poppins', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif`,
    mono: `'JetBrains Mono', 'Fira Code', monospace`,
  },
  styles: {
    'headline-display': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: { base: '34px', md: '42px', lg: '48px' },
      fontWeight: 700,
      lineHeight: { base: '42px', md: '50px', lg: '58px' },
      letterSpacing: '-0.02em',
    },
    'headline-lg': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: { base: '26px', md: '30px', lg: '36px' },
      fontWeight: 600,
      lineHeight: { base: '34px', md: '42px', lg: '58px' },
      letterSpacing: '-0.01em',
    },
    'headline-md': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: { base: '22px', md: '26px', lg: '28px' },
      fontWeight: 500,
      lineHeight: { base: '28px', md: '32px', lg: '34px' },
      letterSpacing: '0px',
    },
    'headline-sm': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: { base: '18px', md: '20px', lg: '21px' },
      fontWeight: 500,
      lineHeight: { base: '24px', md: '25px', lg: '25px' },
      letterSpacing: '0px',
    },
    'body-lg': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: '18px',
      fontWeight: 400,
      lineHeight: '28px',
      letterSpacing: '0px',
    },
    'body-md': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: '24px',
      letterSpacing: '0px',
    },
    'body-sm': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '21px',
      letterSpacing: '0px',
    },
    'label-lg': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: '16px',
      fontWeight: 500,
      lineHeight: '24px',
      letterSpacing: '0px',
    },
    'label-md': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: '14px',
      fontWeight: 400,
      lineHeight: '21px',
      letterSpacing: '0px',
    },
    'label-sm': {
      fontFamily: `'Poppins', sans-serif`,
      fontSize: '12px',
      fontWeight: 400,
      lineHeight: '18px',
      letterSpacing: '0.05em',
    },
  },
} as const;
